const investmentState = { snapshot: null, months: 12, tab: 'active', simulation: null, simulationInput: null };
const pct = value => Number(value).toLocaleString('pt-BR', { maximumFractionDigits: 2 });
const cdbRate = item => item.rateType === 'cdi' ? `${pct(item.rate)}% do CDI` : `${pct(item.rate)}% a.a. prefixado`;
const cdbAmount = value => (value / 100).toFixed(2).replace('.', ',');
function investmentChart(curve) {
  const maximum = Math.max(...curve.map(p => p.gross), 1) * 1.12;
  const x = i => 72 + i / Math.max(curve.length - 1, 1) * 600;
  const y = value => 210 - value / maximum * 170;
  const points = key => curve.map((p, i) => `${x(i)},${y(p[key])}`).join(' ');
  const label = at => new Date(`${at}T12:00:00`).toLocaleDateString('pt-BR', { month: 'short', year: '2-digit' });
  return `<svg class="investment-chart" viewBox="0 0 700 255" role="img" aria-label="Projeção em reais: valor aplicado, saldo bruto e saldo líquido estimado"><defs><linearGradient id="cdb-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#449371" stop-opacity=".22"/><stop offset="100%" stop-color="#449371" stop-opacity=".01"/></linearGradient></defs>${[0, .5, 1].map(r => `<line x1="72" y1="${y(maximum * r)}" x2="672" y2="${y(maximum * r)}" class="grid-line"/><text x="60" y="${y(maximum * r) + 4}" text-anchor="end">${(maximum * r / 100).toLocaleString('pt-BR', { notation: 'compact', maximumFractionDigits: 1 })}</text>`).join('')}<polygon points="72,210 ${points('net')} 672,210" fill="url(#cdb-fill)"/><polyline points="${points('gross')}" class="curve-gross"/><polyline points="${points('principal')}" class="curve-principal"/><polyline points="${points('net')}" class="curve-net"/>${curve.map((p, i) => `<circle cx="${x(i)}" cy="${y(p.net)}" r="4" class="curve-point"><title>${displayDate(p.date)} · líquido ${money(p.net)} · bruto ${money(p.gross)} · aplicado ${money(p.principal)}</title></circle>`).join('')}${[...new Set([0, Math.floor((curve.length - 1) / 2), curve.length - 1])].map(i => `<text x="${x(i)}" y="239" text-anchor="middle">${label(curve[i].date)}</text>`).join('')}</svg><div class="legend investment-legend"><span>━ Líquido estimado</span><span>┄ Bruto estimado</span><span>━ Valor aplicado</span></div>`;
}
function investmentsPage() {
  const s = investmentState.snapshot;
  if (!s) return empty('Preparando sua carteira', 'Carregando os investimentos locais.');
  const active = s.items.filter(item => !item.redeemedDate), projected = s.curve.at(-1);
  const list = s.items.filter(item => investmentState.tab === 'active' ? !item.redeemedDate : item.redeemedDate);
  const upcoming = active.filter(item => item.daysToMaturity <= 30);
  const totalIssuer = new Map();
  for (const item of active) totalIssuer.set(item.issuer, (totalIssuer.get(item.issuer) || 0) + item.principal);
  return `<section class="investment-hero"><div><span class="eyebrow">SEU FUTURO, EM CONSTRUÇÃO</span><h2>O tempo também investe com você.</h2><p>Transforme aportes em planos e acompanhe o caminho até seus objetivos.</p><button class="secondary" data-action="investment-simulate">Explorar um novo plano ↗</button></div><div class="investment-hero-art" aria-hidden="true"><span>01</span><div class="growth-steps"><i></i><i></i><i></i><i></i><i>↗</i></div><small>CONSTÂNCIA + TEMPO</small></div></section>
    <div class="investment-context"><span>Carteira em ${displayDate(s.asOf)} · ${active.length} CDB(s) em acompanhamento</span><button class="link" data-action="investment-settings">CDI ${pct(s.assumptions.cdi)}% a.a. · ${s.assumptions.configured ? 'premissa manual' : 'exemplo editável'} ✎</button></div>
    <section class="metrics investment-metrics">${metric('Capital aplicado', s.totals.principal, '◈', 'balance', 'Aplicações em acompanhamento')}${metric('Saldo líquido estimado', s.totals.net, '↗', 'income', 'Bruto menos IR e IOF estimados')}${metric('Ganho líquido estimado', s.totals.netEarnings, '+', 'income', 'Sobre o capital aplicado')}${metric(`Projeção em ${s.months} meses`, projected.net, '◷', 'pending', 'Líquido · sem novos aportes')}</section>
    <section class="investment-layout"><article class="panel"><div class="panel-heading"><div><h2>O caminho do seu patrimônio</h2><p>Projeção das aplicações em acompanhamento</p></div><select id="investment-horizon" aria-label="Horizonte da projeção">${[3, 6, 12, 24, 60].map(n => `<option value="${n}" ${n === s.months ? 'selected' : ''}>${n} meses</option>`).join('')}</select></div>${active.length ? investmentChart(s.curve) : empty('Seu primeiro CDB começa um plano', 'Cadastre uma aplicação ou experimente o simulador com aportes mensais.')}<p class="hint">Rendimento termina no vencimento. Depois disso, o valor fica constante, sem reinvestimento. Saldo estimado não significa disponibilidade para resgate.</p><details class="investment-details"><summary>Ver valores mês a mês</summary><div class="table-scroll"><table><thead><tr><th>Data</th><th>Aplicado</th><th>Bruto</th><th>IR + IOF</th><th>Líquido</th></tr></thead><tbody>${s.curve.map(p => `<tr><td>${displayDate(p.date)}</td><td>${money(p.principal)}</td><td>${money(p.gross)}</td><td>${money(p.ir + p.iof)}</td><td>${money(p.net)}</td></tr>`).join('')}</tbody></table></div></details></article>
    <aside class="panel investment-radar"><span class="eyebrow">RADAR DA CARTEIRA</span><h2>Próximos passos</h2>${upcoming.length ? upcoming.slice(0, 4).map(item => `<div class="investment-alert"><strong>${esc(item.name)}</strong><p>${item.daysToMaturity < 0 ? 'Vencido: confira o crédito e registre o resgate.' : item.daysToMaturity === 0 ? 'Vence hoje. Confira o valor no banco.' : `Vence em ${item.daysToMaturity} dias · ${displayDate(item.maturityDate)}`}</p><button class="link" data-action="investment-details" data-id="${item.id}">Ver aplicação →</button></div>`).join('') : '<p class="muted">Nenhum vencimento nos próximos 30 dias.</p>'}<h3>Distribuição por emissor</h3>${[...totalIssuer].sort((a, b) => b[1] - a[1]).map(([issuer, amount]) => `<div class="issuer-item"><div><span>${esc(issuer)}</span><strong>${pct(amount / s.totals.principal * 100)}%</strong></div><progress value="${amount}" max="${s.totals.principal}" aria-label="Participação de ${esc(issuer)}"></progress></div>`).join('') || '<p class="hint">A distribuição aparece após seu primeiro cadastro.</p>'}<p class="hint">Confira carência, liquidez e condições no contrato do banco emissor.</p></aside></section>
    <article class="panel investment-wallet"><div class="panel-heading"><div><h2>Sua carteira de CDBs</h2><p>Cada cadastro representa uma aplicação. Novos aportes devem ser cadastrados separadamente.</p></div><div class="investment-tabs" role="group" aria-label="Situação da carteira"><button data-action="investment-tab" data-tab="active" aria-pressed="${investmentState.tab === 'active'}">Em acompanhamento</button><button data-action="investment-tab" data-tab="redeemed" aria-pressed="${investmentState.tab === 'redeemed'}">Resgatados</button></div></div>${list.length ? `<div class="table-scroll"><table class="investment-table"><thead><tr><th>Aplicação / objetivo</th><th>Rentabilidade</th><th>Aplicado</th><th>${investmentState.tab === 'active' ? 'Líquido estimado' : 'Líquido recebido'}</th><th>Vencimento</th><th>Ações</th></tr></thead><tbody>${list.map(item => `<tr><td><strong>${esc(item.name)}</strong><small>${esc(item.issuer)}${item.goal ? ` · ${esc(item.goal)}` : ''}</small></td><td>${cdbRate(item)}<small>${item.liquidity === 'daily' ? 'Liquidez diária' : 'No vencimento'}</small></td><td>${money(item.principal)}</td><td><strong>${money(item.redeemedDate ? item.redeemedNet : item.current.net)}</strong><small>${item.redeemedDate ? `Resgatado em ${displayDate(item.redeemedDate)}` : `IR ${pct(item.current.irRate)}% · IOF ${pct(item.current.iofRate)}%`}</small></td><td>${displayDate(item.maturityDate)}${!item.redeemedDate && item.daysToMaturity < 0 ? '<small class="danger">Conferir resgate</small>' : ''}</td><td><button class="link" data-action="investment-details" data-id="${item.id}">Detalhes →</button></td></tr>`).join('')}</tbody></table></div>` : empty(investmentState.tab === 'active' ? 'Dê um destino ao seu dinheiro' : 'Nenhum resgate registrado', investmentState.tab === 'active' ? 'Use “Novo CDB” para cadastrar a primeira aplicação da família.' : 'Os resgates totais ficam aqui com o valor líquido informado.')}</article>
    <article class="panel investment-scenarios"><div class="panel-heading"><div><h2>E se o CDI mudar?</h2><p>Sensibilidade da carteira em ${s.months} meses, recalculada desde cada aplicação com CDI constante.</p></div><span class="tag">Não é previsão do mercado</span></div><div class="scenario-grid">${s.scenarios.map((scenario, i) => `<div class="scenario ${i === 1 ? 'base' : ''}"><span>${['CDI menor', 'Sua premissa', 'CDI maior'][i]}</span><h3>${pct(scenario.cdi)}% a.a.</h3><strong>${money(scenario.net)}</strong><small>Saldo líquido estimado</small></div>`).join('')}</div><p class="hint">Prefixados mantêm a taxa contratada em todos os cenários. O CDI hipotético é aplicado a todo o período; não representa rentabilidade histórica apurada.</p></article>
    <details class="panel investment-method"><summary>Como calculamos estas projeções</summary><p>Estimativas para pessoa física residente no Brasil, sem taxas, cupons ou resgates parciais. CDI constante e manual, inclusive no período passado. O exemplo inicial de 10% a.a. não é uma cotação atual.</p><p>Juros compostos: base de 252 dias úteis por ano, aproximados por dias corridos × 252/365, sem calendário de feriados. Percentual do CDI aplicado à taxa diária. O extrato do banco é a referência para o saldo real.</p><p>IR sobre o rendimento após IOF: 22,5% até 180 dias; 20% até 360; 17,5% até 720; 15% acima de 720. IOF regressivo nos primeiros 29 dias. No vencimento, rendimento e tributação são congelados.</p><p>Fontes: IN RFB 1.585/2015, art. 46; Decreto 6.306/2007, art. 32 e anexo; Manual do Produto CDB da B3. Referências completas em docs/investimentos-cdb.md. Investimentos não alteram automaticamente receitas, despesas ou saldo do orçamento.</p></details>`;
}
function bindInvestments() {
  document.querySelector('#investment-horizon').addEventListener('change', event => guarded(async () => { investmentState.months = Number(event.target.value); await refresh(); }));
}
function investmentDialog(item) {
  const now = new Date().toLocaleDateString('sv-SE');
  modal(item ? 'Editar CDB' : 'Novo CDB', `<div class="form-grid">${field('Nome da aplicação', 'name', 'text', item?.name || '', 'required maxlength="80" placeholder="Ex.: Reserva de emergência"')}${field('Banco emissor', 'issuer', 'text', item?.issuer || '', 'required maxlength="80" placeholder="Banco que emitiu o CDB"')}${field('Valor aplicado (R$)', 'amount', 'text', item ? cdbAmount(item.principal) : '', 'required inputmode="decimal" placeholder="10000,00"')}${select('Rentabilidade', 'rateType', `<option value="cdi" ${item?.rateType !== 'fixed' ? 'selected' : ''}>Percentual do CDI</option><option value="fixed" ${item?.rateType === 'fixed' ? 'selected' : ''}>Prefixado ao ano</option>`)}${field('Taxa (% do CDI ou % a.a.)', 'rate', 'text', item ? String(item.rate).replace('.', ',') : '100', 'required inputmode="decimal"')}${select('Liquidez contratada', 'liquidity', `<option value="daily" ${item?.liquidity !== 'maturity' ? 'selected' : ''}>Diária, sem carência</option><option value="maturity" ${item?.liquidity === 'maturity' ? 'selected' : ''}>Somente no vencimento</option>`)}${field('Data da aplicação', 'startDate', 'date', item?.startDate || now, `required max="${now}"`)}${field('Vencimento', 'maturityDate', 'date', item?.maturityDate || '', 'required')}${field('Objetivo (opcional)', 'goal', 'text', item?.goal || '', 'maxlength="100" placeholder="Ex.: Viagem, casa, reserva"')}${field('Observações (opcional)', 'notes', 'text', item?.notes || '', 'maxlength="1000"')}</div><p class="hint">Informe uma aplicação por cadastro. 100 em “Percentual do CDI” significa 100% do CDI; 12 em “Prefixado” significa 12% a.a. A carteira não movimenta o orçamento automaticamente.</p>`, 'Salvar CDB', async data => { await call('saveInvestment', { ...data, id: item?.id }); await refresh(); notify('CDB salvo na carteira.'); });
}
function investmentDetails(item) {
  const current = item.current;
  modal(item.name, `<p>${esc(item.issuer)} · ${cdbRate(item)} · ${item.liquidity === 'daily' ? 'Liquidez diária' : 'Resgate no vencimento'}</p><div class="cdb-detail-values"><div><span>Valor aplicado</span><strong>${money(item.principal)}</strong></div><div><span>Bruto estimado</span><strong>${money(current.gross)}</strong></div><div><span>IR estimado (${pct(current.irRate)}%)</span><strong>${money(current.ir)}</strong></div><div><span>IOF estimado (${pct(current.iofRate)}%)</span><strong>${money(current.iof)}</strong></div><div><span>Líquido estimado em ${displayDate(current.date)}</span><strong>${money(current.net)}</strong></div><div><span>Líquido no vencimento</span><strong>${money(item.maturity.net)}</strong></div></div><p>Aplicação: ${displayDate(item.startDate)}<br>Vencimento: ${displayDate(item.maturityDate)}${item.goal ? `<br>Objetivo: ${esc(item.goal)}` : ''}</p>${item.notes ? `<p>${esc(item.notes)}</p>` : ''}${item.redeemedDate ? `<p class="investment-result">Resgate registrado: ${money(item.redeemedNet)} em ${displayDate(item.redeemedDate)}. Resultado líquido informado: ${money(item.redeemedNet - item.principal)}.</p>` : '<p class="hint">Valores indicativos sob a premissa de CDI atual da tela; confira o extrato antes de registrar o valor recebido.</p>'}<div class="investment-detail-actions">${item.redeemedDate ? `<button type="button" class="secondary" data-action="investment-reopen" data-id="${item.id}">Desfazer registro de resgate</button>` : `<button type="button" class="secondary" data-action="investment-edit" data-id="${item.id}">Editar cadastro</button><button type="button" class="primary" data-action="investment-redeem" data-id="${item.id}">Registrar resgate total</button>`}<button type="button" class="link danger" data-action="investment-delete" data-id="${item.id}">Excluir cadastro</button></div>`, 'Fechar', async () => {});
}
function simulationResult(result) {
  return `<div class="simulation-result" aria-live="polite"><span>LÍQUIDO ESTIMADO AO FINAL</span><strong>${money(result.result.net)}</strong><p>Você aplica ${money(result.result.principal)} e estima ${money(result.result.netEarnings)} em ganhos líquidos.</p></div>${investmentChart(result.curve)}<div class="simulation-tax"><span>Bruto: ${money(result.result.gross)}</span><span>IR: ${money(result.result.ir)}</span><span>IOF: ${money(result.result.iof)}</span></div>`;
}
function investmentSimulation() {
  const saved = investmentState.simulationInput || { amount: '10000,00', monthly: '500,00', months: '24', rateType: 'cdi', rate: '100', cdi: String(investmentState.snapshot.assumptions.cdi).replace('.', ',') };
  modal('Um plano para o seu próximo objetivo', `<div class="form-grid">${field('Aplicação inicial (R$)', 'amount', 'text', saved.amount, 'required inputmode="decimal"')}${field('Aporte mensal (R$)', 'monthly', 'text', saved.monthly, 'required inputmode="decimal"')}${field('Prazo (meses)', 'months', 'number', saved.months, 'required min="1" max="120"')}${select('Rentabilidade', 'rateType', `<option value="cdi" ${saved.rateType === 'cdi' ? 'selected' : ''}>Percentual do CDI</option><option value="fixed" ${saved.rateType === 'fixed' ? 'selected' : ''}>Prefixado ao ano</option>`)}${field('Taxa (% do CDI ou % a.a.)', 'rate', 'text', saved.rate, 'required inputmode="decimal"')}${field('CDI hipotético (% a.a.)', 'cdi', 'text', saved.cdi, 'required inputmode="decimal"')}</div><p class="hint">Aportes no fim de cada mês, inclusive no último. Cada aporte tem sua própria idade tributária; todos são liquidados no fim da simulação. Taxas constantes e prazos hipotéticos, sem vínculo com os CDBs cadastrados.</p><button type="button" class="primary" id="run-investment-simulation">Calcular meu plano ↗</button><div id="investment-simulation-result">${investmentState.simulation ? simulationResult(investmentState.simulation) : ''}</div>`, 'Fechar', async () => {});
  const dialog = document.querySelector('dialog'); dialog.classList.add('investment-simulator');
  const button = dialog.querySelector('#run-investment-simulation');
  dialog.querySelector('form').addEventListener('input', () => { investmentState.simulation = null; dialog.querySelector('#investment-simulation-result').innerHTML = '<p class="hint">Premissas alteradas. Clique em calcular para atualizar.</p>'; });
  button.addEventListener('click', () => guarded(async () => {
    const form = dialog.querySelector('form'); if (!form.reportValidity() || button.disabled) return;
    button.disabled = true;
    try { const data = Object.fromEntries(new FormData(form)); investmentState.simulation = await call('simulateInvestment', data); investmentState.simulationInput = data; dialog.querySelector('#investment-simulation-result').innerHTML = simulationResult(investmentState.simulation); }
    finally { button.disabled = false; }
  }));
}
document.addEventListener('click', event => {
  const button = event.target.closest('[data-action^="investment-"]'); if (!button) return;
  guarded(async () => {
    const action = button.dataset.action, item = investmentState.snapshot?.items.find(item => item.id === Number(button.dataset.id));
    if (action === 'investment-new') investmentDialog();
    else if (action === 'investment-edit') investmentDialog(item);
    else if (action === 'investment-details') investmentDetails(item);
    else if (action === 'investment-tab') { investmentState.tab = button.dataset.tab; render(); }
    else if (action === 'investment-settings') modal('Premissas das projeções', `${field('CDI hipotético (% ao ano)', 'cdi', 'text', String(investmentState.snapshot.assumptions.cdi).replace('.', ','), 'required inputmode="decimal"')}<p class="hint">Taxa constante aplicada a todas as projeções, inclusive desde a data de aplicação. Não há consulta online nem série histórica. Alterar a premissa recalcula as estimativas, sem alterar contratos ou resgates registrados.</p>`, 'Salvar premissa', async data => { await call('saveInvestmentSettings', data); await refresh(); notify('Premissa atualizada.'); });
    else if (action === 'investment-delete') confirmDialog('Excluir cadastro de investimento?', 'O cadastro e seu eventual registro de resgate serão excluídos desta carteira. Isso não executa nenhuma operação no banco emissor.', async () => { await call('deleteInvestment', item.id); await refresh(); notify('Cadastro excluído.'); });
    else if (action === 'investment-reopen') confirmDialog('Desfazer registro de resgate?', 'O CDB voltará ao acompanhamento e o valor recebido será removido do histórico desta carteira.', async () => { await call('reopenInvestment', item.id); await refresh(); });
    else if (action === 'investment-redeem') modal('Registrar resgate total', `${field('Data do resgate', 'date', 'date', new Date().toLocaleDateString('sv-SE'), 'required')}${field('Valor líquido recebido (R$)', 'amount', 'text', '', 'required inputmode="decimal" placeholder="Informe o valor do extrato"')}<p class="hint">Informe o valor efetivamente recebido. O registro encerra o acompanhamento desta aplicação; não cria receita no orçamento nem solicita resgate ao banco. Resgates parciais ainda não são suportados.</p>`, 'Registrar resgate', async data => { await call('redeemInvestment', { ...data, id: item.id }); await refresh(); notify('Resgate registrado.'); });
    else if (action === 'investment-simulate') investmentSimulation();
  });
});
