const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const brl = value => (value / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const decimal = value => (value / 100).toFixed(2).replace('.', ',');
function reportCsv(snapshot) {
  const labels = Object.fromEntries(snapshot.paymentTotals.map(p => [p.method, p.label]));
  const cell = value => {
    let s = String(value ?? ''); if (/^[\s]*[=+@-]/.test(s)) s = `'${s}`;
    return `"${s.replaceAll('"', '""')}"`;
  };
  const rows = [['Tipo', 'Descrição', 'Categoria', 'Valor (R$)', 'Vencimento', 'Pagamento', 'Registrado por', 'Observações', 'Natureza', 'Forma de pagamento', 'Cartão', 'Parcela', 'Mês do orçamento', 'Data da compra', 'Despesa contabilizada (R$)', 'Fatura prevista (R$)'], ...snapshot.entries.map(e => [e.type === 'income' ? 'Receita' : 'Despesa', e.description, e.category, decimal(e.amount), e.dueDate, e.paidDate || '', e.author, e.notes, e.kind === 'invoice' ? 'Fatura: somente pagamento' : 'Lançamento de orçamento', labels[e.paymentMethod], e.cardName || '', e.installmentCount > 1 ? `${e.installmentNumber}/${e.installmentCount}` : '', e.budgetMonth || '', e.purchaseDate || '', decimal(e.type === 'expense' && e.kind !== 'invoice' ? e.amount : 0), decimal(e.kind === 'invoice' ? e.amount : 0)])];
  return '\ufeff' + rows.map(row => row.map(cell).join(';')).join('\r\n');
}
function reportHtml(snapshot, month) {
  const labels = Object.fromEntries(snapshot.paymentTotals.map(p => [p.method, p.label]));
  const tableRows = snapshot.entries.map(e => `<tr><td>${escape(e.dueDate)}</td><td>${escape(e.description)}${e.installmentCount > 1 ? ` (${e.installmentNumber}/${e.installmentCount})` : ''}<br><small>${escape(e.category)} · ${escape(labels[e.paymentMethod])}${e.cardName ? ` · ${escape(e.cardName)}` : ''}</small>${e.kind === 'invoice' ? '<br><b>Somente pagamento: não duplica o orçamento</b>' : ''}</td><td>${e.type === 'income' ? 'Receita' : 'Despesa'}</td><td>${brl(e.amount)}</td><td>${escape(e.paidDate || 'Pendente')}</td></tr>`).join('');
  return `<!doctype html><html lang="pt-BR"><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><style>body{font:12px Arial;color:#18372c;margin:32px}h1{font-size:26px}table{border-collapse:collapse;width:100%}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd}thead{display:table-header-group}tr{break-inside:avoid}.totals{padding:16px;background:#eef5ef;margin:20px 0}small,footer{color:#666}footer{margin-top:24px}b{font-size:10px}</style><h1>Saldo Familiar</h1><p>Relatório mensal - ${escape(month)} · Orçamento e pagamentos</p><div class="totals">Receitas: ${brl(snapshot.totals.income)} · Despesas do orçamento: ${brl(snapshot.totals.expense)} · Saldo previsto: ${brl(snapshot.totals.balance)}<br>Pagamentos previstos no mês: ${brl(snapshot.totals.payable)} · Faturas do cartão no mês: ${brl(snapshot.totals.cardDue)}<br>Faturas do cartão no mês seguinte: ${brl(snapshot.totals.nextCardDue)}</div><table><thead><tr><th>Vencimento</th><th>Descrição / forma de pagamento</th><th>Tipo</th><th>Valor</th><th>Pagamento</th></tr></thead><tbody>${tableRows}</tbody></table><h2>Orçamento por categoria</h2>${snapshot.budgets.length ? `<table>${snapshot.budgets.map(b => `<tr><td>${escape(b.category)}</td><td>Limite: ${brl(b.limit)}</td><td>Gastos: ${brl(b.spent)}</td></tr>`).join('')}</table>` : '<p>Nenhum limite cadastrado neste mês.</p>'}<h2>Despesas por forma de pagamento</h2><table>${snapshot.paymentTotals.filter(p => p.amount).map(p => `<tr><td>${escape(p.label)}</td><td>${brl(p.amount)}</td></tr>`).join('')}</table><footer>Gerado em ${escape(new Date().toLocaleString('pt-BR'))}. Parcelas de cartão consomem o orçamento desde o mês da compra; suas faturas representam pagamentos, sem repetir as despesas. Os demais lançamentos continuam classificados por vencimento. O saldo previsto não representa necessariamente o saldo bancário.</footer></html>`;
}
module.exports = { reportHtml, reportCsv };
